blank_issues_enabled: false
contact_links:
  - name: Make a suggestion
    url: https://tailwindui.com/make-a-suggestion
    about: Suggest an idea you'd like to see implemented in a future Tailwind UI update.
