blank_issues_enabled: false
contact_links:
  - name: Get help
    url: https://tailwindui.com/discord
    about: Join the Tailwind UI Discord server to discuss what you're trying to build with others in the community.
